[workspace]
authors = ["Haven Madray <sgpublic2002@gmail.com>"]
channels = ["conda-forge"]
name = "data-engineering-practice"
platforms = ["linux-64"]
version = "0.1.0"
description = "此仓库为王进老师 2025 年硕士研究生选拔办法中，任务一其一（自行练习实验任务 1 ~ 实验任务 33）的记录归档。"
license = "MIT"
readme = "README.md"

[tasks]
# 第一章
task_01 = { cmd = "python -m data_engineering_practice.tasks.task_01" }
task_02 = { cmd = "python -m data_engineering_practice.tasks.task_02" }
task_03 = { cmd = "python -m data_engineering_practice.tasks.task_03" }
homework_01 = { cmd = "python -m data_engineering_practice.homeworks.homework_01" }
# 第二章
task_04 = { cmd = "python -m data_engineering_practice.tasks.task_04" }
task_05 = { cmd = "python -m data_engineering_practice.tasks.task_05" }
task_06 = { cmd = "python -m data_engineering_practice.tasks.task_06" }
task_07 = { cmd = "python -m data_engineering_practice.tasks.task_06" }
task_08 = { cmd = "python -m data_engineering_practice.tasks.task_06" }
task_09 = { cmd = "python -m data_engineering_practice.tasks.task_06" }
task_10 = { cmd = "python -m data_engineering_practice.tasks.task_10" }
task_11 = { cmd = "python -m data_engineering_practice.tasks.task_11" }
task_12 = { cmd = "python -m data_engineering_practice.tasks.task_12" }
task_13 = { cmd = "python -m data_engineering_practice.tasks.task_13" }

[dependencies]
python = ">=3.10, <3.11"
pixi-pycharm = ">=0.0.8, <0.0.9"

[pypi-dependencies]
numpy = ">=2.2.6, <2.3"
pandas = ">=2.3.0, <2.4"
scikit-learn = ">=1.7.0, <1.8"
xgboost = ">=3.0.2, <3.1"
lightgbm = ">=4.6.0, <4.7"

[pypi-options]
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
